---
title: "How to contribute to open projects and communities"
author: "Yani Bellini Saibene"
format: 
  revealjs:
    theme: [default, stilos.scss]
    logo: ropensci.svg
    slide-number: c/t
---

## Path for today

* What a contribution is for a open source project
* ...and for a community?
* Examples with rOpenSci
* How I can help people to contribute to my package?

## Contributions {.winter}


When you listen "Made a **contribution** to an open source project or community"...

...what comes to your mind?


# From a community perspective

We have some models of participation


## Pathway To Inclusion

### Six steps from "never heard of it" to "this is my thing"

::: {.incremental}

* **Awareness**: I've heard of this. 
* **Understanding**:  I understand what this is,and what it might be like for me to be involved.
* **Identification**: I can imagine myself doing this. 
* **Access**: I can physically, logistically, and financially do this. 
* **Belonging**: I feel like I fit in here.
* **Ownership**: I care enough to take responsibility for this.

:::

::: footer
[Pathway To Inclusion by Alex Bayley](https://www.harihareswara.net/posts/2022/the-pathway-to-inclusion-insight-from-alex-bayley/) 
:::

## Pathway To Inclusion {.winter}

::: {.incremental}

At what stage are you with rOpenSci?

Can you give examples for other communities or projects that you are part and in what stage are you?

How long did it take you to move from one state to another?

:::

::: footer
[Pathway To Inclusion by Alex Bayley](https://www.harihareswara.net/posts/2022/the-pathway-to-inclusion-insight-from-alex-bayley/) 
:::

## CSCCE Community Participation Model

::: {.incremental}

* **Convey/Consume**: the CM convey information for members to consume independently of one another.
* **Contribute**: invited/facilitated by the CM. Enables members to discover the skills and interest of other. Made knowledge more visible.
* **Collaborate**: members collaborate with one another. 
* **Co-create**: members work together within the community to co-create something they couldn't do before. 

:::

::: footer
[CSCCE Community Participation Model](https://www.cscce.org/resources/cpm/) 
:::


## CSCCE Community Participation Model {.winter}


* Where you would you put the Champions Program?


## CSCCE Community Participation Model

Champions program are usually in all the spectrum

Examples of champion-ing activities

::: {.incremental}

* **Convey**: they post on social media to spread the word more widely

* **Contribute**: they invite others to attend a event;

* **Collaborate**: they host a community call;

* **Co-create**: they run trainings or other activities for others in the community

:::

::: footer
[CSCCE Community Participation Model](https://www.cscce.org/resources/cpm/) 
:::

## rOpenSci Examples

* [rOpenSci Community Contributing Guide](https://contributing.ropensci.org): a guide to help people find ways to contribute to rOpenSci

* [rOpenSci Blog Guide](https://blogguide.ropensci.org): a guide to help people to write and edit blog post for rOpenSci Blog.

* [rOpenSci Packages: Development, Maintenance, and Peer Review](https://devguide.ropensci.org): guide for package authors, maintainers, reviewers and editors in rOpenSci software peer-review system

* [rOpenSci Statistical Software Peer Review](https://stats-devguide.ropensci.org): documentation of rOpenSci’s project on expanding software peer review to include statistical software.

## rOpenSci Examples {.winter}

::: {.incremental}

* Have you participate in any of this options?

* Which one would you like to try?

* You can use many of this options as your outreach activity for the Champions Program.

* We would like to learn how we can improve this activities.

* Spread the word about this options to people in your communities.

::: 


# How this concepts are useful for my package ?

## Convey

* Create a comprehensive [README](https://blog.r-hub.io/2019/12/03/readmes/): clearly explains what your package does, how to install it, and how users can start using it. Include examples or use cases and (links to) any relevant information which might help users understand how your package can help them.

* [Pin your package repository to your profile](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/pinning-items-to-your-profile) so other people can find it quickly.

* [Create a universe on R-universe](https://ropensci.org/blog/2021/06/22/setup-runiverse/), simplify the installation of your package, and provide useful stats and information about it.

## Convey

* We recommend creating a **documentation website** for your package using pkgdown. 

* Leverage platforms like Mastodon, LinkedIn, and R-specific forums such as [R-bloggers](https://www.r-bloggers.com/) and [R Weekly](https://rweekly.org/) to announce the release of your package.

* If you like to give talks, you can speak at an R User Group or [R-Ladies Chapter](https://www.meetup.com/pro/rladies/).

* Presenting your package at a **domain-specific conference** or at R-specific conferences.

* If your package fits in a [CRAN Task View](https://cran.r-project.org/web/views/) you can propose the addition.

## Contribute

Make your repo contribution and collaboration friendly

* Code of conduct (`CODE_OF_CONDUCT.md`): you can insert one with `use_code_of_conduct()` from the `usethis` package. The template comes from https://www.contributor-covenant.org.

* OSI License (`LICENSE.md`).

* Contributing guide (`CONTRIBUTING.md`): an easy way to insert a template for a contributing guide is the `use_tidy_contributing()` from the `usethis` package.

## Contributing guide

Personal preferences in a contributing guide include:

* Style preferences? 

* Infrastructure like roxygen2?

* Workflow preferences? Issue before a PR?

* Describe how you acknowledge contributions. 

* A scope statement, like in the [skimr](https://github.com/ropensci/skimr/blob/main/.github/CONTRIBUTING.md#understanding-the-scope-of-skimr) package?

* We encourages contributing guides to include a [lifecycle statement clarifying visions and expectations](https://github.com/ecohealthalliance/fasterize/blob/main/CONTRIBUTING.md#roadmap) for the future development of your package.

## Issue management

